### ISSUE TITLE
Logging mechanism

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/nrdk#15]
Adopt and use a consistent logging framework (as opposed to `console.log`). [winston](https://github.com/winstonjs/winston) seems to be a popular one in the nodejs community

**Comment by DerekRoberts** [comment]
Users specify logging level
Cosistent logging
https://github.com/winstonjs/winston

**Comment by DerekRoberts** [comment]
There's a bunyan example in a temporary branch that won't be merged.  Please install bunyan, view the example output and remove the junk files.  In an *empty directory* run the following:

```
npm i bunyan
wget -qO- https://raw.githubusercontent.com/BCDevOps/nrdk/logging/src/util/bunyan-example.js | node
rm -rf node_modules/ package.json package-lock.json
```

**Comment by DerekRoberts** [comment]
Bunyan has the following advantages over Winston and not much in the way of shortcomings:

- [CLI tool](https://github.com/trentm/node-bunyan#cli-usage) for filtering logs
- [Child loggers](https://github.com/trentm/node-bunyan#logchild) for subcommands/topics
- [Serializers](https://github.com/trentm/node-bunyan#serializers), defaulting output to JSON
- [Lighter](https://www.npmjs.com/package/bunyan) in size / dependencies at 201 kb / 4 deps vs 286 kb / 9 deps for [winston](https://www.npmjs.com/package/winston)
- [Support](https://github.com/trentm/node-bunyan#runtime-environments) for Webpack and Browserify
- [Push](https://github.com/benbria/node-bunyan-lumberjack) logs to Elastic's [Logstash](https://www.elastic.co/logstash)
- [dtrace-provider](https://github.com/trentm/node-bunyan#runtime-log-snooping-via-dtrace) support to separate app from node logs

**Comment by DerekRoberts** [comment]
Looks like we're going with Winston, but in a farily separate process to allow flexibility down the road.
