### ISSUE TITLE
make npm scripts platform independent

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/nrdk#39]
we have already introduces `cross-env`, I think [npm-run-all](https://www.npmjs.com/package/npm-run-all) may also be a good addition and help us remove all the `&&` which is linux  only

**Comment by DerekRoberts** [comment]
Scripts:
    "watcher": "npm i && watch 'npm run build' src",
    "prebuild": "oclif-dev manifest",
    "build": "tsc -b",
    "postpack": "rm -f oclif.manifest.json",
    "postbuild": "cpx 'src/**/*.yaml' lib",
    "lint": "eslint . --ext .ts --config .eslintrc",
    "posttest": "eslint . --ext .ts --config .eslintrc",
    "prepack": "rm -rf lib && tsc -b && oclif-dev manifest && oclif-dev readme && cpx 'src/**/*.{yaml,groovy}' lib",
    "ncc": "ncc build bin/run -o dist --minify",
    "test": "cross-env NOCK_BACK_MODE=lockdown nyc --reporter=html --reporter=text --extension .ts mocha --timeout 99999 --grep \"@type=system\" --invert --forbid-only \"test/**/*.test.ts\"",
    "mocha:all": "mocha --forbid-only --grep \"@type=system\" --invert --timeout 99999 \"test/**/*.test.ts\"",
    "mocha": "mocha --timeout 9999999",
    "version": "oclif-dev readme && git add README.md",
    "oclif": "oclif",
    "link": "npm link @bcgov/nr-pipeline-ext && npm link @bcgov/pipeline-cli",
    "publish:latest": "npm --no-git-tag-version version prerelease && npm publish --tag latest",
    "publish:alpha": "npm --no-git-tag-version version prerelease && npm publish --tag alpha"

**Comment by DerekRoberts** [comment]
Win 10 fails:
- watcher
- postpack
- prepack
- ncc

**Comment by DerekRoberts** [comment]
Re: cross-env and npm-run-all

They haven't been required so far.  Maybe on the next pass!

**Comment by DerekRoberts** [comment]
Waiting for PR review.  Ticket stays open until then.
