### ISSUE TITLE
nrdk greetings command

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/nrdk#55]
As a Developer
I need to understand how to add commands to nrdk
so that I can understand how nrdk works and effectively contribute to the project

DoD:
- create the greetings command by running `npm run oclif -- greetings`
- `npx @bcgov/nrdk greetings`  should output 'Hello World'
- `npx @bcgov/nrdk greetings Earth`  should output 'Hello Earth'
- Be able to  put a breakpoint and inspect what is going to be printed before printing
- Have unit tests valid and passing by running `npm run mocha -- "test/**/<greeetings>.test.ts"`

Reference:
- https://oclif.io/docs/generator_commands#oclif-command-name
- https://oclif.io/docs/testing
-

**Comment by DerekRoberts** [comment]
@cvarjao https://github.com/BCDevOps/nrdk/pull/57
